import { Poppins } from "next/font/google";
import { Lexend } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const poppins = Poppins({
  weight: ["200", "800"],
  subsets: ["latin"],
  variable: "--font-poppins",
});
const lexend = Lexend({
  weight: ["200", "800"],
  subsets: ["latin"],
  variable: "--font-lexend",
  title: "Create Next App",
  description: "Generated by create next app",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} ${lexend.variable}`}>
      <body suppressHydrationWarning>
        <Header />

        <main>{children}</main>

        <Footer />
      </body>
    </html>
  );
}
