import { Poppins } from "next/font/google";
import { Lexend } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const poppins = Poppins({
  weight: ["200", "800"],
  subsets: ["latin"],
});
const lexend = Lexend({
  weight: ["200", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Header />

        <main>{children}</main>

        <Footer />
      </body>
    </html>
  );
}
